# Generated by Django 6.0 on 2026-01-01 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lexeme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("zh", "Chinese"),
                            ("fi", "Finnish"),
                        ],
                        db_index=True,
                        max_length=2,
                    ),
                ),
                ("text", models.CharField(db_index=True, max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["language", "text"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("language", "text"), name="uniq_lexeme_lang_text"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Term",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "en",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="term_en",
                        to="vocab.lexeme",
                    ),
                ),
                (
                    "fi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="term_fi",
                        to="vocab.lexeme",
                    ),
                ),
                (
                    "zh",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="term_zh",
                        to="vocab.lexeme",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("en", "zh", "fi"), name="uniq_term_triplet"
                    )
                ],
            },
        ),
    ]
